Milestone 3: Add Contact form
MNisarAli/Portfolio pull request #3
Opened 2022-11-09 08:37 UTC by TumiRantsane

## Add the contact form and finish the Mobile version.
- Make sure that:
  - Name field accepts up to 30 chars.
  - Email field accepts only emails.
  - Message field accepts up to 500 chars.
  - All fields have placeholder text.
  - All fields have the correct type.
  - A user cannot submit the form if one or more of the fields is empty.
- To collect user data, use the [Formspree service](https://formspree.io/html).
- To lay out the elements, use Flexbox.
- Implement the button interactions (enable, hover, etc.).

2022-11-09 14:45 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-   No linter errors. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark: 
-   Good README file. :heavy_check_mark: 
-   Descriptive PR title and summary. :heavy_check_mark: 

![](https://camo.githubusercontent.com/77566116408d88259ddadf7605a02b67a4e825e002a39682ca5f2e8bca8c4d64/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 14:45 UTC, Qoosim commented on index.html
> +            <input type="text" name="user-email" id="email" placeholder="example@gmail.com" required>
- [ ] The `<input type="email">` defines a field for an e-mail address. The input value is automatically validated to ensure it is a properly formatted e-mail address. Kindly attend to that and fix it.

2022-11-09 14:57 UTC, MNisarAli commented on index.html
> +            <input type="text" name="user-email" id="email" placeholder="example@gmail.com" required>
Thanks for your review. I have made the required changes to `<input type=>` as `<"email">`

2022-11-09 15:15 UTC, Debas-31 approved these changes
> ## Hi @MNisarAli  :wave:, 

# Status: Approved :heavy_check_mark: 

Great work on making the changes requested by a previous reviewer. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/fYlennPcKut8gjKOZD/giphy.gif"/>

## Highlights
- PR title and summary :heavy_check_mark: 
- Commit message :heavy_check_mark:
- Project functionality :heavy_check_mark: 
- UI design :heavy_check_mark: 
- Figma template usage :heavy_check_mark: 

## Optional suggestions
- [ ] No

***Cheers and Happy coding!👏👏👏***

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 15:18 UTC, merged

2022-11-10 07:55 UTC, DianaBeki commented on index.html
> +      <h2 class="get-started">Get started</h2>
- Please i suggest in your h2 element you would have used a class-like heading-2 for someone to understand your code easily while styling.